# Generated by Django 3.1.1 on 2020-09-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_remove_djangoclasses_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(default=0),
        ),
    ]
